### ISSUE TITLE
Broken link on your page

### ISSUE THREAD

**Issue by kartikp1995** [dhruvkb/dhruvkb.github.io#1]
Link on your webpage is broken. 
Also, instead of creating a folder in Repository, create a separate repository for different project. :+1:

**Comment by dhruvkb** [comment]
I'll make it right soon. That site was just a placeholder, BTW. I'm making my app on my laptop at the moment and will figure out how to move it to Heroku later.

**Comment by dhruvkb** [comment]
Transferred.
